[2024-02-07T13:15:32.744+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver-search-pipeline.store_naver manual__2024-02-07T04:15:24.103293+00:00 [queued]>
[2024-02-07T13:15:32.747+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver-search-pipeline.store_naver manual__2024-02-07T04:15:24.103293+00:00 [queued]>
[2024-02-07T13:15:32.747+0900] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-07T13:15:32.757+0900] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): store_naver> on 2024-02-07 04:15:24.103293+00:00
[2024-02-07T13:15:32.759+0900] {standard_task_runner.py:57} INFO - Started process 145357 to run task
[2024-02-07T13:15:32.760+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'naver-search-pipeline', 'store_naver', 'manual__2024-02-07T04:15:24.103293+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/naver_search_pipeline.py', '--cfg-path', '/tmp/tmp62r11top']
[2024-02-07T13:15:32.761+0900] {standard_task_runner.py:85} INFO - Job 20: Subtask store_naver
[2024-02-07T13:15:32.779+0900] {task_command.py:410} INFO - Running <TaskInstance: naver-search-pipeline.store_naver manual__2024-02-07T04:15:24.103293+00:00 [running]> on host localhost
[2024-02-07T13:15:32.815+0900] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='naver-search-pipeline' AIRFLOW_CTX_TASK_ID='store_naver' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T04:15:24.103293+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-07T04:15:24.103293+00:00'
[2024-02-07T13:15:32.816+0900] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-07T13:15:32.816+0900] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n.import /home/shan/airflow/dags/data/processed_result.csv naver_search_result" | sqlite3 /home/shan/airflow/airflow.db']
[2024-02-07T13:15:32.819+0900] {subprocess.py:86} INFO - Output:
[2024-02-07T13:15:32.820+0900] {subprocess.py:93} INFO - Error: cannot open "/home/shan/airflow/dags/data/processed_result.csv"
[2024-02-07T13:15:32.820+0900] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-07T13:15:32.824+0900] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shan/anaconda3/envs/airflow_env/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-07T13:15:32.825+0900] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=naver-search-pipeline, task_id=store_naver, execution_date=20240207T041524, start_date=20240207T041532, end_date=20240207T041532
[2024-02-07T13:15:32.833+0900] {standard_task_runner.py:109} ERROR - Failed to execute job 20 for task store_naver (Bash command failed. The command returned a non-zero exit code 1.; 145357)
[2024-02-07T13:15:32.852+0900] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-07T13:15:32.861+0900] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
